
import type { Voice, Emotion, NarrationStyle, Accent, SpecialEffect } from './types';

// FIX: Capitalize voice IDs to match the expected format for the Gemini API's `voiceName` parameter.
// FIX: Add language codes and use valid API voice IDs for all non-English voices.
export const VOICES: Voice[] = [
  {
    id: 'kore-en-us',
    apiId: 'Kore',
    name: 'Kore',
    language: 'English (US)',
    languageCode: 'en-US',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-kore.png',
    tag: 'Narrator',
    gender: 'Female',
  },
  {
    id: 'puck-en-us',
    apiId: 'Puck',
    name: 'Puck',
    language: 'English (US)',
    languageCode: 'en-US',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-puck.png',
    tag: 'Announcer',
    gender: 'Male',
  },
  {
    id: 'charon-en-gb',
    apiId: 'Charon',
    name: 'Charon',
    language: 'English (UK)',
    languageCode: 'en-GB',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-charon.png',
    tag: 'Storyteller',
    gender: 'Male',
  },
  {
    id: 'zephyr-en-gb',
    apiId: 'Zephyr',
    name: 'Zephyr',
    language: 'English (UK)',
    languageCode: 'en-GB',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-zephyr.png',
    tag: 'Assistant',
    gender: 'Female',
  },
  {
    id: 'anjali-hi-in',
    apiId: 'Kore', 
    name: 'Anjali',
    language: 'Hindi',
    languageCode: 'hi-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Conversational',
    gender: 'Female',
  },
  {
    id: 'rohan-hi-in',
    apiId: 'Puck', 
    name: 'Rohan',
    language: 'Hindi',
    languageCode: 'hi-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Friendly',
    gender: 'Male',
  },
  {
    id: 'krishna-ta-in',
    apiId: 'Charon',
    name: 'Krishna',
    language: 'Tamil',
    languageCode: 'ta-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Formal',
    gender: 'Male',
  },
  {
    id: 'kavya-ta-in',
    apiId: 'Zephyr',
    name: 'Kavya',
    language: 'Tamil',
    languageCode: 'ta-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Expressive',
    gender: 'Female',
  },
   {
    id: 'riya-bn-in',
    apiId: 'Kore',
    name: 'Riya',
    language: 'Bengali',
    languageCode: 'bn-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-riya.png',
    tag: 'Friendly',
    gender: 'Female',
  },
  {
    id: 'aarav-bn-in',
    apiId: 'Puck',
    name: 'Aarav',
    language: 'Bengali',
    languageCode: 'bn-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Calm',
    gender: 'Male',
  },
  {
    id: 'divya-te-in',
    apiId: 'Zephyr',
    name: 'Divya',
    language: 'Telugu',
    languageCode: 'te-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Expressive',
    gender: 'Female',
  },
  {
    id: 'naveen-te-in',
    apiId: 'Charon',
    name: 'Naveen',
    language: 'Telugu',
    languageCode: 'te-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Clear',
    gender: 'Male',
  },
  {
    id: 'aarohi-mr-in',
    apiId: 'Kore',
    name: 'Aarohi',
    language: 'Marathi',
    languageCode: 'mr-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-riya.png',
    tag: 'Gentle',
    gender: 'Female',
  },
  {
    id: 'suresh-mr-in',
    apiId: 'Puck',
    name: 'Suresh',
    language: 'Marathi',
    languageCode: 'mr-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-puck.png',
    tag: 'Professional',
    gender: 'Male',
  },
  {
    id: 'rupa-gu-in',
    apiId: 'Zephyr',
    name: 'Rupa',
    language: 'Gujarati',
    languageCode: 'gu-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Sweet',
    gender: 'Female',
  },
  {
    id: 'parth-gu-in',
    apiId: 'Charon',
    name: 'Parth',
    language: 'Gujarati',
    languageCode: 'gu-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Confident',
    gender: 'Male',
  },
  {
    id: 'sahana-kn-in',
    apiId: 'Kore',
    name: 'Sahana',
    language: 'Kannada',
    languageCode: 'kn-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-riya.png',
    tag: 'Melodious',
    gender: 'Female',
  },
  {
    id: 'ravi-kn-in',
    apiId: 'Puck',
    name: 'Ravi',
    language: 'Kannada',
    languageCode: 'kn-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-puck.png',
    tag: 'Rich',
    gender: 'Male',
  },
  {
    id: 'anu-ml-in',
    apiId: 'Zephyr',
    name: 'Anu',
    language: 'Malayalam',
    languageCode: 'ml-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-kore.png',
    tag: 'Warm',
    gender: 'Female',
  },
  {
    id: 'rajesh-ml-in',
    apiId: 'Charon',
    name: 'Rajesh',
    language: 'Malayalam',
    languageCode: 'ml-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-charon.png',
    tag: 'Deep',
    gender: 'Male',
  },
  {
    id: 'simran-pa-in',
    apiId: 'Kore',
    name: 'Simran',
    language: 'Punjabi',
    languageCode: 'pa-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Vibrant',
    gender: 'Female',
  },
  {
    id: 'harpreet-pa-in',
    apiId: 'Puck',
    name: 'Harpreet',
    language: 'Punjabi',
    languageCode: 'pa-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Strong',
    gender: 'Male',
  },
  {
    id: 'isha-or-in',
    apiId: 'Zephyr',
    name: 'Isha',
    language: 'Odia',
    languageCode: 'or-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-riya.png',
    tag: 'Clear',
    gender: 'Female',
  },
  {
    id: 'animesh-or-in',
    apiId: 'Charon',
    name: 'Animesh',
    language: 'Odia',
    languageCode: 'or-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-puck.png',
    tag: 'Formal',
    gender: 'Male',
  },
  {
    id: 'alakananda-as-in',
    apiId: 'Kore',
    name: 'Alakananda',
    language: 'Assamese',
    languageCode: 'as-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-kore.png',
    tag: 'Melodious',
    gender: 'Female',
  },
  {
    id: 'bikram-as-in',
    apiId: 'Puck',
    name: 'Bikram',
    language: 'Assamese',
    languageCode: 'as-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-charon.png',
    tag: 'Rich',
    gender: 'Male',
  },
  {
    id: 'fatima-ur-in',
    apiId: 'Zephyr',
    name: 'Fatima',
    language: 'Urdu',
    languageCode: 'ur-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-anjali.png',
    tag: 'Eloquent',
    gender: 'Female',
  },
  {
    id: 'zayn-ur-in',
    apiId: 'Charon',
    name: 'Zayn',
    language: 'Urdu',
    languageCode: 'ur-IN',
    avatarUrl: 'https://storage.googleapis.com/aai-web-samples/avatar-krishna.png',
    tag: 'Deep',
    gender: 'Male',
  },
];

export const EMOTIONS: Emotion[] = [
  'Neutral', 
  'Happy', 
  'Sad', 
  'Angry', 
  'Cheerful', 
  'Calm', 
  'Excited', 
  'Amused', 
  'Joyful', 
  'Hopeful', 
  'Terrified', 
  'Disgusted', 
  'Fearful', 
  'Whispering', 
  'Serious', 
  'Formal',
  'Sarcastic',
  'Worried',
  'Curious',
  'Ashamed',
  'Confused',
  'Enthusiastic',
  'Disappointed',
  'Proud'
];

export const NARRATION_STYLES: NarrationStyle[] = ['Default', 'Storytelling', 'Poetry'];

export const ACCENTS_BY_LANGUAGE: { [key: string]: Accent[] } = {
  'English': ['Default', 'US English', 'UK English', 'Indian English', 'Australian English', 'Scottish English', 'Irish English', 'South African English'],
  'Hindi': ['Default', 'Mumbai', 'Delhi', 'Punjabi', 'Hyderabadi', 'Lucknowi', 'UP', 'Bihari', 'Rajasthani', 'Bhojpuri', 'Haryanvi'],
  'Tamil': ['Default', 'Chennai', 'Coimbatore', 'Madurai', 'Sri Lankan', 'Hyderabadi', 'Tirunelveli'],
  'Bengali': ['Default', 'Kolkata', 'Dhaka', 'Bengali (Indian)', 'Sylheti'],
  'Telugu': ['Default', 'Telangana', 'Andhra', 'Hyderabadi', 'Rayalaseema'],
  'Marathi': ['Default', 'Pune', 'Nagpur', 'Mumbai', 'Konkani'],
  'Gujarati': ['Default', 'Ahmedabad', 'Surat', 'Kathiawadi'],
  'Kannada': ['Default', 'Bengaluru', 'Mangalore', 'Mysuru'],
  // FIX: Correct 'Kozhikode' to 'Kozhod' to match the Accent type definition.
  'Malayalam': ['Default', 'Kochi', 'Kozhod', 'Trivandrum'],
  'Punjabi': ['Default', 'Amritsari', 'Ludhianvi', 'Punjabi', 'Majha'],
  'Odia': ['Default', 'Bhubaneswari', 'Cuttacki', 'Sambalpuri'],
  'Assamese': ['Default', 'Guwahati', 'Jorhat', 'Upper Assam'],
  'Urdu': ['Default', 'Karachi', 'Lahori', 'Delhi', 'Lucknowi', 'Deccani'],
};

export const SPECIAL_EFFECTS: { id: SpecialEffect; name: string }[] = [
  { id: 'None', name: 'None' },
  { id: 'Devil', name: 'Devil Voice' },
  { id: 'Robot', name: 'Robot Voice' },
  { id: 'Ghost', name: 'Ghost Voice' },
  { id: 'Dual', name: 'Dual Voice (Echo)' },
];
